### PR TITLE
content

### PR DESCRIPTION
**Pull request by chunningham**
all new banners, filled out text content, links should work in both
dropdown and sidebar, incl. active

TODO: footer links, maybe split content pages into products and services, make sidebar look better and play nice with content frame.

also, are we including a certification page? i couldnt find a link anywhere

### CODE REVIEW

**Comment by ichpuchtli** [comment]
All the links I included were there just as a template I didn't actually consider the layout of the content so do whatever you see fit regarding links / content.

**Comment by ichpuchtli** [comment]
``` html
<div class="container"> 

  <div class="col col-tablet-4">
    <div class="card" id="sidebar">
       <ul>
         <li></li>
       </ul>
     </div>
  </div>

  <div class="col col-tablet-8">
    <div class="card">
      <h1>Aeration</h1>
        <p>
          ...
        </p>
    </div>
  </div>

</div>
```

**Comment by ichpuchtli** [comment]
Just need this for your sidebar styles

``` css
#sidebar > ul {
  list-style: none;
  padding: 0;
}

#sidebar > ul > li {
  padding-top: 5px;
  padding-bottom: 5px;
}
```

**Comment by ichpuchtli** [comment]
Looking good.

My fix earlier regarding the banner sizes should fix those issues we're seeing.

Btw you can check it out here.

https://chunningham.github.io/wet-redesign/

**Comment by ichpuchtli** [comment]
For the certification images. Add this to the main.css.

``` css

.card > img {
  width: 100%;
}
```

**Comment by ichpuchtli** [comment]
Those banner captions a cringeworthy haha I like it.

**Comment by chunningham** [comment]
couple of minor problems I still can't figure out. one of the cards on the gallery page won't go where it should, but when I open the page locally it's fine. Also, active links are only coloured in the basic header, not in the dropdown menu or in the product/service sidebars

**Comment by chunningham** [comment]
also reckon 8 images in the gallery is enough? tbh i reckon it is

**Comment by chunningham** [comment]
and oddly enough the gallery sorts itself out only when you make the window thinner

**Comment by ichpuchtli** [comment]
1. When you shrink the home page the banner caption is still 'Banner Caption 5'
2. I think the second column in the footer should be `.col-tablet-3` instead of `.col-tablet-2`
3. the phone icon has to be removed from the top menu as its effecting smaller devices

**Comment by ichpuchtli** [comment]
For the gallery. Put each group of 4 `.col-tablet-3`'s in its own container. ie.

``` html
<div class="container">
  <div class="col col-tablet-3"></div>
  <div class="col col-tablet-3"></div>
  <div class="col col-tablet-3"></div>
  <div class="col col-tablet-3"></div>
</div>
<!-- This will create a new row -->
<div class="container">
  <div class="col col-tablet-3"></div>
  <div class="col col-tablet-3"></div>
  <div class="col col-tablet-3"></div>
  <div class="col col-tablet-3"></div>
</div>

```

**Comment by chunningham** [comment]
the footer has (currently) 2 2 3 3 1, if i make the 2's 3's it become 13/12, but if they're 2's its 9/12, what do you reckon i should do? they dont look too bad as 2's but there's a gap on the right side then

**Comment by ichpuchtli** [comment]
I'm off  @chunningham ,   you may have to merge this manually.

You will have to add my repo as a remote to pull the changes I made after your forked. Before submitting.

**Comment by ichpuchtli** [comment]
no just make the second column a 3

**Comment by chunningham** [comment]
real quick, how do I add your repo as a remote?

**Comment by ichpuchtli** [comment]
https://stackoverflow.com/questions/3903817/pull-new-updates-from-original-github-repository-into-forked-github-repository

**Comment by ichpuchtli** [comment]
```
$ cd wet-redesign
$ git remote add upstream https://github.com/ichpuchtli/wet-redesign
$ git fetch upstream
```

then: (like "git pull" which is fetch + merge)  

```
$ git merge upstream/gh-pages gh-pages
```

**Comment by ichpuchtli** [comment]
Good luck.

**Comment by chunningham** [comment]
cheers, lets see how this goes haha

**Comment by chunningham** [comment]
I think it worked...

**Comment by chunningham** [comment]
Charless-MacBook-Air:wet-redesign charlescunningham$ git remote add upstream https://github.com/ichpuchtli/wet-redesign
Charless-MacBook-Air:wet-redesign charlescunningham$ git fetch upstream
From https://github.com/ichpuchtli/wet-redesign
- [new branch]      gh-pages   -> upstream/gh-pages
- [new branch]      master     -> upstream/master
- [new branch]      windows-fixes -> upstream/windows-fixes
  Charless-MacBook-Air:wet-redesign charlescunningham$ git merge upstream/gh-pages gh-pages
  Auto-merging css/main.css
  Auto-merging contact.html
  error: There was a problem with the editor 'vi'.
  Not committing merge; use 'git commit' to complete the merge.
  Charless-MacBook-Air:wet-redesign charlescunningham$ git commit
  [gh-pages 667f34b] Merge remote-tracking branch 'upstream/gh-pages' into gh-pages

**Comment by chunningham** [comment]
dropdown menu and carousel dont work when run locally, is that a problem?

**Comment by chunningham** [comment]
/if i now just download as a zip from by repo page is that the right one? cos thats the one i'm submitting tonight

**Comment by chunningham** [comment]
/also i dont have the statement of delivery, so thats not in there

**Pull request merged**
